ZanichelliEditore/design-system

- src/components/navigation/z-header/index.spec.ts
- src/components/navigation/z-header/index.tsx
This PR enhances classlist generation with template literals. With the previous implementation, checks like `${!this.ismyz && "myz-out"}` often resulted in having `false` between the classes of the elements. This happens when the first operand is evaluated to `false`, because of the `&&` operator [**Short-circuit evaluation**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND).
> Avoid `false` in header element classes

- src/globals/global-border-and-radius.css
- src/globals/global-colors.css
- src/globals/global-fonts.css
- src/globals/global-grid.css
- src/globals/global-spacing.css
This PR fixes a compatibility issue with Edge which does not support `:host` selector. Since those variables are used in the main context only, we do not really need that selector at all.
> Remove host selector from root variable for edge compatibility

- src/components/inputs/z-input/styles-select.css
Fixes #52 
* Limit `ul` width
* Wrap `li` and inner `span` content and go on next line if the string is very long and overflows.
> chore: limit width, go on next line for very long strings

- src/components/navigation/z-header/styles.css
This PR fixes z-header second row height (now it's hidden when it's empty)
> fix: z-header second row height

- src/components.d.ts
- src/components/card/z-card-dictionary/index.spec.ts
- src/components/card/z-card-dictionary/index.stories.mdx
- src/components/card/z-card-dictionary/index.tsx
- src/components/card/z-card-dictionary/readme.md
- src/components/card/z-card-dictionary/styles.css
- src/index.html
Feature: MYZ-7754 
added "hideinfobtn" prop to ZCardDictionary
----
To be able to use it on "AddOrTryDictionary" modal.
ref: https://zanichelli.atlassian.net/browse/MYZ-7754
> feat: MYZ-7754 added hideinfobtn prop to ZCardDictionary

- package.json
The `unpkg` field in the current `package.json` points to a nonexistent bundle. As per [unpkg docs](https://unpkg.com/):
> If you omit the file path (i.e. use a “bare” URL), unpkg will serve the file specified by the `unpkg` field in `package.json`, or fall back to `main`.
With the current release (1.7.0, at the time of this writing), the request is being redirected to `dist/web-components-library.js`, but the file is not included in the dist files. The correct path would be `dist/web-components-library/web-components-library.esm.js`, as it is correctly documented in this project's README.
This happens, for instance, when including the script as a "bare" URL (<https://unpkg.com/@zanichelli/albe-web-components>), and the browser gets redirected to the aforementioned missing path, which …
> Chore - Fix path to bundle served via unpkg

- src/components.d.ts
- src/components/icons/z-icon/styles.css
With latest modify to z-button (for slot), z-icon width/height properties are violated by "inherit" CSS rules previously added.
The result is that z-icon width/height properties  are not used correctly.
This small PR fixes this side-effect refining the CSS rules. 
----
> Fix Z-Icon style

- src/components/buttons/z-chip/index.spec.ts
- src/components/buttons/z-chip/index.stories.mdx
- src/components/buttons/z-chip/index.tsx
- src/index.html
Adds support to custom slots and maintains backwards compatibility with the previous implementation.
The request arises from the need to add typography elements customized with different colors.
https://app.abstract.com/projects/fd370780-e659-11e8-99dc-0d08537c5fde/branches/master/commits/e23f154e523fbe380233e3edab892dfe962349da/files/2B453759-9259-472B-8098-2846C9D506B5/layers/BFC98A10-F410-4D40-BFE8-B4486B0F2CA9?collectionLayerId=4adbe381-83ab-44a5-8716-97a9c67e69fb&mode=design
----
> Z-Chip with slots, keeping retrocompatibility

- src/components/inputs/z-combobox/index.spec.ts
- src/components/inputs/z-combobox/index.tsx
- src/components/inputs/z-combobox/readme.md
----
Default state of z-combobox must be "closed".
This change would not be breaking for MyZ/Classi Virtuali.
----
> Feature - z-combobox - changed default state to closed

- src/components/navigation/z-user-dropdown/styles.css
> fix: fixed padding and margin

- src/snowflakes/registro-table/z-registro-table-header/index.stories.mdx
- src/snowflakes/registro-table/z-registro-table-header/index.tsx
----
Keep the current sort arrow even clicking on a non sortable header
----
> Feat - z-registro-table-header - fix sorting clicking on a non-sortable header

- src/components.d.ts
- src/snowflakes/registro-table/z-registro-table-header/index.tsx
- src/snowflakes/registro-table/z-registro-table-header/readme.md
----
Add default sort value
----
> Feature - ZRegistroTableHeader - Add default sort to value

- src/snowflakes/registro-table/z-registro-table-expanded-row/styles.css
----
with this pr the shadow under the expandable row of the table has been added
before
after
> Chore - Add shadow below ZRegistroTableExpandedRow

- src/snowflakes/registro-table/z-registro-table-row/index.tsx
----
disable click on Expandable-Row when clicking on Contextual-Menu
----
> Fix - Disable click on Expandable-Row when clicking on Contextual-Menu

- src/snowflakes/registro-table/z-registro-table/styles.css
----
Related stories: [CLAV-174](https://zanichelli.atlassian.net/browse/CLAV-174) and [CLAV-166](https://zanichelli.atlassian.net/browse/CLAV-166)
With this bugfix:
- we remove the min-height (288px) set to the empty table, allowing it the expand vertically according to the content inside
- we add a border at the bottom of the table content in case of empty table
> Fix - Ztable - remove min-height / add border bottom to empty table

- src/snowflakes/registro-table/z-registro-table-empty-box/index.spec.ts
- src/snowflakes/registro-table/z-registro-table-empty-box/index.tsx
- src/snowflakes/registro-table/z-registro-table/index.spec.ts
- src/snowflakes/registro-table/z-registro-table/index.tsx
Related to [CLAV-166](https://zanichelli.atlassian.net/browse/CLAV-166) and [CLAV-174](https://zanichelli.atlassian.net/browse/CLAV-174): with this PR we improve how the empty table is rendered.
**Before**:
**After**:
> Fix - ZTable - Empty box border and height

- src/snowflakes/registro-table/z-registro-table-expanded-row/index.stories.mdx
- src/snowflakes/registro-table/z-registro-table-expanded-row/index.tsx
- src/snowflakes/registro-table/z-registro-table-expanded-row/styles.css
Related to [CLAV-239](https://zanichelli.atlassian.net/browse/CLAV-239), we must handle different spacing and border width mobile users. With this PR we remove ALL rules related to spacing (margin and padding) and border. These properties will be handle by the content inside the component.
> Refactor - ZRegistroTableExpandedRow - remove spacing and border rules

- src/components.d.ts
- src/components/navigation/z-app-header/index.tsx
- src/components/navigation/z-app-header/readme.md
----
Emits event when header enters or exits stuck mode.
----
> chore: added sticking event

- src/components/z-popover/index.tsx
With the following PR, we solve a weird behaviour of ZPopover and related components. On trigger click the popover content according to the [popover position](https://github.com/ZanichelliEditore/design-system/blob/master/src/beans/index.tsx#L214) set by the developer. 
In case the open popover-content size exceeds the viewport, this is positioned programmatically according to the original configuration. 
In some cases, the position wasn't calculated correctly, e.g. the trigger is positioned below the fold and the user scroll the page.
Related to [CLAV-304](https://zanichelli.atlassian.net/browse/CLAV-304)
A Pull Request to be merged must have two approvals, one from a member of the product team who developed it and another from a member of the dst dev team other than the team …
> Fix - ZPopover/ZContextualMenu - Fix popover content positioning inside the viewport

- src/components/inputs/z-input/index.tsx
- src/components/inputs/z-input/test-text.spec.ts
> Fix - ZInput - Added `type="button"` to icon buttons to prevent form submit

- src/components/navigation/z-app-header/index.spec.ts
- src/components/navigation/z-app-header/index.tsx
- src/components/navigation/z-app-header/styles.css
----
The `ZAppHeader` component used to dinamically set the stuck mode offset based on the `ZAppTopbar` component height.
The `ZAppTopbar` component is not longer user in the `IdpLogin` component, so the offset is always set to 0 and breaks the stuck mode.
----
> Fix - ZAppHeader - Removed offset setting

- src/components/inputs/z-input/styles-text.css
Force background color to white to prevent Chrome light blue background on inputs with autocomplete prop (login form).
> fix: force autocomplete input background color

- src/components/z-offcanvas/index.spec.ts
- src/components/z-offcanvas/index.tsx
BTH-5920 - while trying to integrate the appswitcher into idp-login-component, we encountered an issue with the component briefly flashing on the screen before sliding in as it should. 
This PR is meant as a workaround. A more structural refactoring might be advisable.
> Fix - z-offcanvas - avoid double rendering upon opening

- src/components/inputs/z-combobox/index.tsx
Fix - Z-Combobox - fix render loop on props change when search is populated
> fix: avoid render loop

- src/components/z-offcanvas/index.tsx
- src/components/z-offcanvas/styles.css
While the pushcontent variant is meant to be displayed alongside the content of the page itself, the overlay variant is meant to cover it and only leave the offcanvas contents accessible. The ability to scroll the page's content causes a double scrollbar to appear on the right. this, while useful for the pushcontent variant, is completely unneeded in the overlay variant and is thus being excluded.
> fix: z-offcanvas - block page scroll for overlay variant

- CHANGELOG.md
- package.json
- src/components/inputs/z-searchbar/index.tsx
This PR fixes the situation in which a string containing a "(", followed by at least two character, is typed in the searchbar as a search term avoiding :
`SyntaxError: Invalid regular expression`.
More generally this pull request solves all the situations in which a user enters a regex in the search field performing a string replacement operation on the searchString property by escaping any characters that have a special meaning in a regular expression.
To reproduce the error:
1. create a searchbar with these two properties:
autocomplete="true" 
autocomplete-min-chars="3"
2. provide an array of resultsItems with a label, for example:
`[
{
"label": "first item ed value"
}
]`
2.  Type in the searchbar _(ed_ and
Expected exception:
`SyntaxError: Invalid regular expression: /(ed/:`
> fix: z-searchbar add escape characters to handle nested regex

- package.json
- src/components/modal/z-modal/index.spec.ts
- src/components/modal/z-modal/index.tsx
- src/components/modal/z-modal/styles.css
- yarn.lock
Add dialog polyfill for old browsers support
Old browser (ie: Safari < 15.4) do not support native dialog tag. This polyfill solve the issue
> fix: add dialog polyfill for old browsers

- src/components/z-card/index.tsx
PR che fixa un bug della z-card su un check per decidere se emittare o meno l'evento click. Questo causava l'emit dell'evento `click` quando quest'ultimo veniva da un element figlio di uno slot `action`, mentre veniva correttamente skippato solo per gli element con l'attributo `slot=action`.
> Fix - z-card - skip click event emission also for children of a slotted `action`

- MIGRATION.md
- src/components.d.ts
- src/components/z-card/index.spec.ts
- src/components/z-card/index.stories.css
- src/components/z-card/index.stories.mdx
- src/components/z-card/index.tsx
- src/components/z-card/readme.md
- src/components/z-card/styles.css
- src/themes/index.stories.css
- src/themes/index.stories.mdx
Al momento la `z-card` non è accessibile per i seguenti motivi, principalmente:
- l'attributo "clickable" crea un finto elemento interattivo, facendo sì che semanticamente rimanga nel DOM un elemento "z-card" non noto agli strumenti assistivi. Questi ultimi non possono capire che la "z-card" è potenzialmente interattivo, e non lo gestiranno come tale
- questo crea problemi di accessibilità ma anche problemi legati all'indicizzazione dei contenuti: in molti casi la z-card è usata come link ma non viene renderizzata come tale, né per gli utenti né per i crawler
- non c'è modo di avere un elemento "tabbabile" come un link o un bottone da inserire nei vari slot. O meglio, questo è  possibile, ma al momento si perderebbe la gestione dell'interazione (il click) con l'intera card se si vuole …
> Z-Card Accessibility fix

- src/components/z-carousel/index.tsx
When the direct li element of the container has a list of other li elements, the component also counts them to add the dots
> Fix multiple li in z-carousel

- src/components/navigation/z-app-header/index.spec.ts
- src/components/navigation/z-app-header/index.tsx
- src/components/navigation/z-app-header/styles.css
> Fix - ZAppHeader - Always render mobile menu slot

- src/components/z-breadcrumb/index.tsx
Very simple PR that just removes an unwanted whitespace on breadcrumb template only on mobile viewport.
> Whitespace on breadcrumb mobile

- src/components.d.ts
- src/components/z-book-card/index.spec.ts
- src/components/z-book-card/index.stories.mdx
- src/components/z-book-card/index.tsx
- src/components/z-book-card/readme.md
- src/components/z-book-card/styles.css
The new `ribbonIcon` prop allows the user to add an icon on the left side of ribbon text. 
When the `ribbonInteractive` is set to true, the component emits an `ribbonClick` event on click.
> Feat/z book card/ribbon icon and cta

- src/components/navigation/z-navigation-tabs/index.tsx
- src/themes/index.stories.css
This PR fixes a bug that caused the component to disappear when resizing the window. The bug was caused by Stencil that, for some reason, wasn't being able to place the slotted elements in their original place after a conditionally rendered element (in this case the first navigation button) and rendered an empty `<nav>` element instead.
Using the `hidden` attribute on the buttons instead of the conditional render, fixed the bug.
This PR also fixes the implementation of the focus and keyboard navigation: when leaving the tabs after a keyboard navigation having a selected tab and then focusing again the tabs, the focus was given to the last focused tab instead of the selected one, as indicated by the [Tabs pattern](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/).
> Fix - z-navigation-tabs - component disappearing on resize

- src/components/inputs/z-select/index.spec.ts
- src/components/inputs/z-select/index.tsx
During testing on the Z-Select a11y improvements, we noticed that `z-list` has not aria-label property. 
This fix the issue.
> chore: z-select / add aria-label to z-list

- src/components/z-offcanvas/index.tsx
- src/components/z-offcanvas/styles.css
> fix: z-offcanvas increased css specificity handle unmount

- src/components/z-carousel/index.stories.css
- src/components/z-carousel/index.tsx
This PR fixes the visibility of navigation buttons for the `infinite` mode.
Now the validity check doesn't assume the navigation buttons should be always visible when `infinite` is set to `true`, instead it follows the conditions set for `single` and default mode, then the render function decides whether to show or not the buttons and takes into account the `infinite` prop to set the `disabled` attribute.
> Fix - ZCarousel - nav buttons' visibility

- src/components/z-info-reveal/index.stories.css
- src/components/z-info-reveal/index.stories.mdx
- src/components/z-info-reveal/index.tsx
- src/components/z-info-reveal/styles.css
- src/components/z-popover/index.stories.css
- src/components/z-popover/index.stories.mdx
Implementation of component restyling. Also handled info panel in non-desktop viewport.
https://www.figma.com/file/w51ZwDwLNEt0yamar2sRRQ/branch/Semo75xq0khkRRw15Vt3UC/Nuovi-Componenti-e-Pattern?type=design&node-id=4743%3A8001&mode=design&t=RAenRdhR2YlG6umA-1
Some CSSProp to change the colors of the component (and probably never used), has been removed in favor of the theming semantic CSSProps. Should we consider this change as breaking?
> Refactor - z-info-reveal - restyling

- src/components.d.ts
- src/components/z-anchor-navigation/index.stories.css
- src/components/z-anchor-navigation/index.stories.ts
- src/components/z-anchor-navigation/index.tsx
- src/components/z-anchor-navigation/readme.md
- src/components/z-anchor-navigation/styles.css
- src/utils/utils.ts
- stencil.config.ts
This PR adds a prop named `autoCurrent` to the `ZAnchorNavigation` component, to allow disabling the default behavior on highlighting the current anchor. By setting `autoCurrent` to `false`, highlighting a slotted child can be done by setting the `data-current` attribute. NB: the `aria-current` attribute on the `<a>` elements, if needed, must be set manually.
> Feat - ZAnchorNavigation - manual anchor highlight

- src/components/z-popover/index.tsx
This PR fixes the `getParentElement` function of the ZPopover component: the old condition to get the `host` of a `shadowRoot` did not consider the existence of the `host` field of anchor HTML elements, so when the `parentNode` is an anchor, the URL's host was considered a `shadowRoot`'s host.
> Fix - ZPopover - fix parent element finder function when checking shadow root

- src/components/z-input/index.tsx
- src/components/z-input/styles.css
When importing the design system in a Stencil project, `styleUrls` (introduced in `v14.5.2`) does not work as expected and some styling is lost. This PR restore the previous working solution.
> fix: apply styles correctly on Stencil projects

- src/components/z-tag/index.spec.ts
- src/components/z-tag/index.tsx
- src/components/z-tag/styles.css
This PR improves the way the `z-tag` component uses the `--z-tag-bg` and `--z-tag-text-color` to set the style, allowing the apps to change the value without using `!important` in a selector with less specificity of the scoping css class set by stencil. Also, the `body-5-sb` typography class has been removed, setting the relative styles directly, as setting a different class (for example `body-3-sb`) wouldn't work.
> fix - z-tag - improve CSS variables usage

- src/components/z-carousel/index.tsx
Remove `group` role from carousel items and items container. The role was not exactly wrong but it's not necessary in a "list context" with `ul` and `li`s. That roles were causing an error with accessibility check tools like **axe DevTools**.
> Chore - z-carousel - remove wrong roles

- src/components/z-modal/index.tsx
When opening the modal an overflow-y: hidden; was added to the body in mobile view. This caused a problem when closing the modal because the overflow was not removed and the page did not scroll anymore.
The overflow was added in a previous pr to fix the scrolling of the body under the modal when it was open.
> fix: z-modal - remove overflow-y

- .eslintignore
- .eslintrc.json
- src/components.d.ts
- src/components/deprecated/z-book-card-deprecated/index.spec.ts
- src/components/file-upload/z-dragdrop-area/index.spec.ts
- src/components/file-upload/z-dragdrop-area/index.tsx
- src/components/file-upload/z-dragdrop-area/readme.md
- src/components/file-upload/z-dragdrop-area/styles.css
- src/components/file-upload/z-file-upload/index.spec.ts
- src/components/file-upload/z-file-upload/index.stories.ts
- src/components/file-upload/z-file-upload/index.tsx
- src/components/file-upload/z-file-upload/readme.md
- src/components/file-upload/z-file-upload/styles.css
- src/components/file-upload/z-file-upload/test.e2e.ts
- src/components/z-button/readme.md
- src/components/z-divider/readme.md
- src/components/z-searchbar/index.spec.ts
- src/utils/storybook-utils.ts
This PR fixes some style and removes the shadow to let the file input be visible inside a form.
Also, it introduces 2 new prop, `inputName` to set the value of the `name` attribute of the `input` and `showErrors` that, when set to `false`, allows the apps to manually handle upload errors instead of the ones previously showed by the component inside a `z-modal`. Another related change is the emission of the new `fileError` event, sending to the app the upload errors with an object containing the file name and a list of errors:
```ts
{
file: string; // file name
errors: { cause: "size" | "format", messages: string }[];
}
```
https://www.figma.com/design/Tu6D9gzAOgOJw9Nf1an91K/Z_main_library_master?node-id=3738-10526&m=dev
> Fix - z-file-upload

- src/components/z-accordion/styles.css
- src/components/z-anchor-navigation/styles.css
- src/components/z-menu-section/styles.css
- src/components/z-menu/styles.css
- src/components/z-navigation-tabs/styles.css
This PR fixes some color issue caused by the usage of the `secondary` color token in various components, after the value change made in the v17 release.
> Fix - usage of color tokens

- src/components/book-card/z-book-card/index.stories.ts
- src/components/book-card/z-book-card/index.tsx
- src/components/book-card/z-book-card/styles.css
- src/pages/book-cards.html
In this PR is add a slot inside the z-book-card cover enabling a purple overlay on the cover img, for display purpose
[Link to figma](https://www.figma.com/design/To5LlfWLba1S62IkOS3VxM/Book-card-2024?node-id=12122-2630&t=0BpVRVp6WTym0y0D-4)
> feat: add preview slot to z-book-card-cover

- src/components.d.ts
- src/components/z-modal/index.stories.ts
- src/components/z-modal/index.tsx
- src/components/z-modal/readme.md
- src/components/z-modal/test.e2e.ts
> Z modal/block page scroll

- src/components/file-upload/z-file-upload/index.tsx
The component failed to delete an uploaded file, because the method `removeFile`received an object instead of the string identifying the file name
> Fix z-file-upload

- src/components.d.ts
- src/components/z-icon/index.spec.ts
- src/components/z-icon/index.stories.ts
- src/components/z-icon/index.tsx
- src/components/z-icon/readme.md
- src/components/z-icon/styles.css
Add unit dimensions params for z-icon. Now you can use `width` and `height` like a number (in pixels by default) or use another unit dimension like `px`, `%`, `em`, `ex`, `pt`,  `pc`, `cm`, `mm`, `in` for ZIcon.
> Feat - ZIcon - Add unit dimensions params

- src/components/z-info-reveal/styles.css
This PR fixes the positioning of the `z-info-reveal` component on mobile viewports.
Previously, the component was using `position: fixed`, causing it to stay fixed during page scroll
It also changes the z-index of said component to avoid overlapping the `z-app-header`
> fix: info reveal position on mobile

- MIGRATION.md
- src/tokens/themes/dark-default.css
The default token assigned to background for the dark theme has been removed uniforming it to other themes.
> fix: remove background from dark theme

- src/components/z-navigation-tabs/index.tsx
A avoid auto scroll on loading ZNavigationTabs
If `ZNavigationTabs` has a child element with `aria-selected="true"`, it will automatically be scrolled into view, potentially causing the page to scroll to the position of that child.
When clicking the rightmost visible item ( on a long list of items ) on a navigation tab, if the click happens close to the outer edge, sometimes the scroll behavior would trigger before the click could be registered, causing the click event to be lost. This fix ensures that the click is properly handled in such cases.
> fix: avoid auto scroll on loading ZNavigationTabs
