readme.md
This PR fixes package name in the README after it has been renamed and added to the `@zanichelli` organisation.
=> chore: update package name

src/components/notification/z-pocket/index.tsx
ZPocket toggle event improvement.
=> MYZ-7114 fix toggle event

src/components/modal/z-modal/styles.css
This PR fixes position and top margin of the modal, as per graphic design specifications
=> fix: modal margin top and positioning

src/components/card/z-card-footer/index.spec.ts, src/components/card/z-card-footer/index.tsx, src/components/card/z-card-header/index.tsx
MYZ-7191 Added tooltip to z-card elements (header and footer). Tooltip is enabled only if ellipsis exists.
=> MYZ-7191 cards tooltip.

src/components/notification/z-pocket/index.spec.ts, src/components/notification/z-pocket/index.tsx, src/components/notification/z-pocket/styles.css
=> MYZ-7114 swipe

src/beans/index.tsx, src/components.d.ts, src/components/indicators/z-stepper-item/index.spec.ts, src/components/indicators/z-stepper-item/index.stories.mdx, src/components/indicators/z-stepper-item/index.tsx, src/components/indicators/z-stepper-item/readme.md, src/components/indicators/z-stepper-item/styles.css, src/components/indicators/z-stepper/index.spec.ts, src/components/indicators/z-stepper/index.stories.mdx, src/components/indicators/z-stepper/index.tsx, src/components/indicators/z-stepper/readme.md, src/components/indicators/z-stepper/styles.css, src/index.html
integrate stepper snowflake component
=> feat: stepper component

src/beans/index.tsx, src/components.d.ts, src/components/indicators/z-stepper-item/index.spec.ts, src/components/indicators/z-stepper-item/index.stories.mdx, src/components/indicators/z-stepper-item/index.tsx, src/components/indicators/z-stepper-item/readme.md, src/components/indicators/z-stepper-item/styles.css, src/components/indicators/z-stepper/index.spec.ts, src/components/indicators/z-stepper/index.stories.mdx, src/components/indicators/z-stepper/index.tsx, src/components/indicators/z-stepper/readme.md, src/components/indicators/z-stepper/styles.css, src/index.html
**⚠️ THIS ELEMENT IS A SNOWFLAKE, DO NOT MERGE THE PR ⚠️**
This PR introduces the new Stepper component. At the moment, the abstract link is missing because this element is still a proposal.
=> Stepper component

src/components/navigation/z-header/styles.css
This PR fixes int links overflow and automatically adjusts int links and ext links width
=> fix z-header links overflow and positioning

src/components/inputs/z-otp/styles.css
Z-OTP snowflake component css fixes
=> MYZ-7055 css fix

src/components/inputs/z-input/styles-general.css
fixed z-input component for edge compatibility
- set ::ms-reveal to display:none
=> fix edge password default reveal

internals/generators/component/styles.css.hbs, src/components/footer/z-footer/index.tsx, src/components/footer/z-footer/styles.css, src/components/inputs/z-input/styles-checkbox.css, src/components/inputs/z-input/styles-radio.css, src/components/navigation/z-header/styles.css, src/components/navigation/z-menu-dropdown/styles.css, src/constants/grid.json, src/globals/global-grid.css, yarn.lock
This PR fixes wrong breakpoints for footer and navigation bar components. It also updates *safe* references in the project in order to prevent future inconsistencies.
fixes #5
=> Footer and navigation bar  breakpoints

src/components/inputs/z-input/styles-text.css
=> fix: add more padding so text does not overlap X button on zinput text

src/components/indicators/z-stepper/readme.md
Fix old attribute `status` for `z-stepper` component.
=> fix: z-stepper docs

src/components.d.ts, src/components/buttons/z-toggle-button/index.spec.ts, src/components/buttons/z-toggle-button/index.stories.mdx, src/components/buttons/z-toggle-button/index.tsx, src/components/buttons/z-toggle-button/readme.md, src/index.html
=> Feature - z-toggle-button - MYZ-7574 added opened prop

src/components.d.ts, src/components/card/z-card-dictionary/index.spec.ts, src/components/card/z-card-dictionary/index.tsx, src/components/card/z-card-dictionary/readme.md, src/components/card/z-card-info/index.spec.ts, src/components/card/z-card-info/index.tsx, src/components/card/z-card-info/readme.md
=> Modified Event flipCard and inserted accessibility

.commitlintrc.json, package.json, yarn.lock
https://zanichelli.atlassian.net/browse/BTH-5037
Currently, husky stable version is 4.3.8 but there is a @next release 5.0.6 that requires some [breaking changes](https://typicode.github.io/husky/#/?id=breaking-changes)
We decided to install the stable version.
----
=> feat: add and configure husky and commitlint packages

src/components.d.ts, src/components/card/z-card-footer/index.spec.ts, src/components/card/z-card-footer/index.tsx, src/components/card/z-card-footer/readme.md, src/components/card/z-card-footer/styles.css, src/components/card/z-card-header/index.tsx, src/components/card/z-card-list/styles.css, src/index.html
----
ZCard component restyle. 
https://app.abstract.com/projects/fd370780-e659-11e8-99dc-0d08537c5fde/branches/435673a7-8bdd-460b-a163-989e47deb4c0/collections/bc2a54a0-201f-4935-be84-7ee07bd027d3
=> Chore - z-card - z-card refactoring

src/components/indicators/z-stepper-item/index.spec.ts
----
this PR fixes zStepperItem unit test
=> fix: zStepperItem test

src/components/card/z-card-info/index.tsx
Fix - z-card-info - Added componentWillLoad method
----
----
=> MYZ-7619 fix: added componentWillLoad method

package.json, src/components/card/z-card-alert/styles.css, src/components/card/z-card-footer/styles.css, src/components/navigation/z-menu-dropdown/styles.css, src/index.html, yarn.lock
----
This PR 
- integrate @zanichelli/albe-design-tokens@1.0.63 version
- fixes specified component styles missing by chore/design-tokens refactoring
- restores index.html page for basic dev purpose
----
=> fix: design-tokens missing style

.github/workflows/storybook.yml
----
Due to action failed job, the action needs to be updated using node version 14
----
=> feat: updated setup-node@v2 in storybook release workflow

src/beans/index.tsx, src/components/notification/z-tooltip/index.spec.ts, src/components/notification/z-tooltip/index.stories.mdx, src/components/notification/z-tooltip/index.tsx, src/components/notification/z-tooltip/readme.md, src/components/notification/z-tooltip/styles.css
Currently, the `z-tooltip` handles only a text content. It should handle arbitrary content to have, for example, tooltip with buttons or links.
Also, changed the way the "type" property (direction of popup) is handled, making it possible to change it at runtime - this modify is visible using the Storybook and changing "type" Knob: now it works as expected.
Also:
- removed border, not present from abstract
- added all the 9 tooltip position (initially only 4 were available)
- handled dark/light mode
----
=> Z-Tooltip with slots, keeping retrocompatibility

src/beans/index.tsx, src/components.d.ts, src/components/navigation/z-app-topbar/styles.css, src/components/navigation/z-user-dropdown/index.tsx, src/components/navigation/z-user-dropdown/readme.md, src/components/navigation/z-user-dropdown/test.e2e.ts
----
This PR adds an Event fired on dropdown menu link click to help handle link click (es.: logout)
----
=> chore: added z-user-dropdown menu link click event

src/components/icons/z-icon/readme.md, src/components/navigation/z-app-switcher/index.spec.ts, src/components/navigation/z-app-switcher/index.tsx, src/components/navigation/z-app-switcher/readme.md, src/components/navigation/z-app-switcher/styles.css, src/components/navigation/z-user-dropdown/styles.css
----
This PR adds max-width to z-user-dropdown menu and app-switcher icon
https://app.abstract.com/projects/fd370780-e659-11e8-99dc-0d08537c5fde/branches/master/commits/8efc43f91fc365cd9c339c393cc8f56f91374286/files/7e5534c1-96e2-44c2-98f8-965c34ee8835/layers/7BC1646B-F8EC-4466-A720-AEBAFFC3ABF0?collectionId=ecb94390-fedf-428f-b021-4d452c356519&collectionLayerId=85fa2859-469c-48a5-86d4-2cc1a95f622f&mode=design
----
=> chore: added zpp-switcher icon and z-user-dropdown max-width

src/components/notification/z-tooltip/index.stories.mdx, src/components/notification/z-tooltip/styles.css
Some z-tooltip naming positions were wrong; we fixed them and also added a separate story for each z-tooltip position along with an auxiliary component in order to understand the z-tooltip "type" prop semantics. Also, added a story for the dark mode style.
----
=> Fixed z-tooltip positions and enhanced storybook

src/components/icons/icons.tsx
----
ask-your-manager icon retrocompatibility fix (support icon)
----
=> fix: ask-your-manager icon fix

src/components/buttons/z-chip/index.tsx, src/index.html
----
If z-chip boldtext prop is 0, no boldtext field was rendered, due to field wrong nullity check. This fix implements correct nullity check.
----
=> fix: fix z-chip nullish checks

src/components/notification/z-tooltip/index.stories.mdx, src/components/notification/z-tooltip/styles.css
Fix z-tooltip legacy style and apply new styles to the regular version.
Fix:
- re-added legacy border
Style updates:
- indicator size
- shadow
- min height
- min width
- padding
- font style
- border radius
https://app.abstract.com/projects/fd370780-e659-11e8-99dc-0d08537c5fde/branches/2dfe4495-dae7-4dd1-a957-6ce44c423cb9/commits/latest/files/2B453759-9259-472B-8098-2846C9D506B5/layers/3FCBDAC6-0860-4E81-97C7-50176DBCDA8F?collectionId=39c677ff-9536-46bc-899c-802a3de461ee&collectionLayerId=400acf59-cf44-45b7-9db2-03bed8506c89&mode=build&selected=319405477-44CD8B9E-8EAB-4F89-9C73-F215A8B90DDD
https://app.abstract.com/projects/fd370780-e659-11e8-99dc-0d08537c5fde/branches/01019965-1940-4b65-b1a6-3e2fc3635003/commits/latest/files/9f586aa0-bd5b-4c12-9541-aed2e98a7a9c/layers/D7A7438B-7BB9-4021-9 …
=> refactor - z-tooltip - style updates and fix

.storybook/preview.js, src/components.d.ts, src/components/icons/z-icon/readme.md, src/components/navigation/z-app-header/index.spec.ts, src/components/navigation/z-app-header/index.stories.css, src/components/navigation/z-app-header/index.stories.mdx, src/components/navigation/z-app-header/index.tsx, src/components/navigation/z-app-header/readme.md, src/components/navigation/z-app-header/styles.css, src/components/navigation/z-app-topbar/styles.css, src/components/navigation/z-menu-section/styles.css, src/components/navigation/z-menu/index.spec.ts, src/components/navigation/z-menu/index.tsx, src/components/navigation/z-menu/styles.css
----
This PR introduces some layouts required by the original design specs for the App Header, such as the inline and the offcanvas menu and the stuck state.
**Known issues and limitations**
* The abstract specifies a size for the offcanvas panel that relies on the grid system and it needs to be reviewed (component is outside the grid).
* The `stuck` state layout has been implemented but cannot be automatically set since it is part of a larger pattern which should include the topbar.
https://app.abstract.com/projects/fd370780-e659-11e8-99dc-0d08537c5fde/branches/0c0f3a4b-c77f-421b-857a-40df36455ea1/commits/bd0e05fd10cb1dcb25b30a0cce7aa900f90d9329/files/9f586aa0-bd5b-4c12-9541-aed2e98a7a9c/layers/4E523230-5E7F-4CA2-A228-9670D60C3030?collectionId=98002816-a2d9-48f1-880a-2e6854ac2181&collecti …
=> Header+menu layouts

src/beans/index.tsx, src/components.d.ts, src/components/buttons/z-button/readme.md, src/components/icons/z-icon/readme.md, src/components/z-popover/index.tsx, src/components/z-popover/readme.md, src/index.html, src/snowflakes/registro-table/z-registro-table-header/index.spec.ts, src/snowflakes/registro-table/z-registro-table-header/index.stories.mdx, src/snowflakes/registro-table/z-registro-table-header/index.tsx, src/snowflakes/registro-table/z-registro-table-header/readme.md, src/snowflakes/registro-table/z-registro-table-header/styles.css
----
add styles and functions to table header [story](https://zanichelli.atlassian.net/browse/CLAV-69)
[link](https://app.abstract.com/projects/4ad7d17c-8133-465e-9926-09f387eef58a/branches/d6520888-030a-4878-9c38-77501e3ee6a9/commits/latest/files/6ccb681e-7ab6-4f9d-8a06-c04e9ced92d1/layers/15C10898-66E4-460D-8102-A5CE44CFA41C?collectionId=0ad8ccad-ffef-42eb-9eb4-1a164e7f6b94&collectionLayerId=30e430cf-9573-482a-93e9-d822f8e640b5)
----
=> feat - z-registro-table-header - add style and functions to table header

src/beans/index.tsx, src/components.d.ts, src/components/icons/z-icon/readme.md, src/components/typography/z-body/readme.md, src/components/z-popover/index.stories.mdx, src/components/z-status-tag/index.spec.ts, src/components/z-status-tag/index.stories.mdx, src/components/z-status-tag/index.tsx, src/components/z-status-tag/readme.md, src/components/z-status-tag/styles.css, src/index.html
----
Add new graphic element: z-status tag ([story](https://zanichelli.atlassian.net/browse/CLAV-44))
[abstract](https://app.abstract.com/share/b8ae04de-5a0f-4ae7-8eab-7829d02a0eb3?mode=design&sha=2bb82d792c779961d592b26c125b5aac7fba35f6)
----
=> component - z-status-tag - add new component

src/components/z-status-tag/index.spec.ts
=> chore - z-status-tag - fix broken test

src/components.d.ts, src/components/icons/z-icon/readme.md, src/index.html, src/snowflakes/registro-table/z-registro-table-body/styles.css, src/snowflakes/registro-table/z-registro-table-cell/index.spec.ts, src/snowflakes/registro-table/z-registro-table-cell/index.tsx, src/snowflakes/registro-table/z-registro-table-cell/readme.md, src/snowflakes/registro-table/z-registro-table-expanded-row/index.spec.ts, src/snowflakes/registro-table/z-registro-table-expanded-row/index.stories.mdx, src/snowflakes/registro-table/z-registro-table-expanded-row/index.tsx, src/snowflakes/registro-table/z-registro-table-expanded-row/readme.md, src/snowflakes/registro-table/z-registro-table-expanded-row/styles.css, src/snowflakes/registro-table/z-registro-table-header-row/index.spec.ts, src/snowflakes/registro-table/z-registro-table-header-row/index.stories.mdx, src/snowflakes/registro-table/z-registro-table-header-row/index.tsx, src/snowflakes/registro-table/z-registro-table-header-row/readme.md, src/snowflakes/registro-table/z-registro-table-header-row/styles.css, src/snowflakes/registro-table/z-registro-table-header/index.spec.ts, src/snowflakes/registro-table/z-registro-table-header/index.tsx, src/snowflakes/registro-table/z-registro-table-header/readme.md, src/snowflakes/registro-table/z-registro-table-header/styles.css, src/snowflakes/registro-table/z-registro-table-row/index.tsx, src/snowflakes/registro-table/z-registro-table-row/readme.md, src/snowflakes/registro-table/z-registro-table-row/styles.css, src/snowflakes/registro-table/z-registro-table/index.stories.mdx, src/snowflakes/registro-table/z-registro-table/styles.css
----
Table row can expand show more content.
[Story](https://zanichelli.atlassian.net/browse/CLAV-41)
[Abstract](https://app.abstract.com/projects/fd370780-e659-11e8-99dc-0d08537c5fde/branches/63ca3ba6-5cf7-4b1a-8483-2dd6507523c3/commits/latest/files/9f586aa0-bd5b-4c12-9541-aed2e98a7a9c/layers/21C06C14-CCF3-4A1C-8B48-DD34F7D81ED9?collectionId=d83a525e-c241-45be-8cc2-636a3a761631&collectionLayerId=cbde06da-cf1f-44b8-a8ba-50e9f6952c6e)
There are some difference agreed with uix. Ex: expand button spacing, expanded row shadow
----
=> feat - z-registro-table-row - snowflake expandable row

CHANGELOG.md, package.json, src/beans/index.tsx, src/components.d.ts, src/components/z-avatar/index.spec.ts, src/components/z-avatar/index.stories.mdx, src/components/z-avatar/index.tsx, src/components/z-avatar/readme.md, src/components/z-avatar/styles.css, src/index.html
----
Add new component [(story)](https://zanichelli.atlassian.net/browse/CLAV-42)
[link](https://app.abstract.com/projects/fd370780-e659-11e8-99dc-0d08537c5fde/branches/master/commits/e5a3ba0efe6dc4a8a0bfdb67a1f3af205f31037d/files/2B453759-9259-472B-8098-2846C9D506B5/layers/F58D9440-C5CC-495F-8347-CFF9EF4E844E?mode=design&sha=e5a3ba0efe6dc4a8a0bfdb67a1f3af205f31037d)
----
=> component - z-avatar - add new component

src/components.d.ts, src/components/navigation/z-navigation-tab/index.spec.ts, src/components/navigation/z-navigation-tab/index.tsx, src/components/navigation/z-navigation-tab/readme.md, src/components/navigation/z-navigation-tab/styles.css, src/components/navigation/z-navigation-tabs/index.spec.ts, src/components/navigation/z-navigation-tabs/index.stories.mdx, src/components/navigation/z-navigation-tabs/index.tsx, src/components/navigation/z-navigation-tabs/styles.css
----
Improvements to:
- scroll handling
- tab focus
- hover + focus
- add theming variables
- button text wrapping for long text
=> Fix ZNavigation tab/tabs

src/snowflakes/registro-table/z-registro-table/styles.css
----
fix ZRegistroTable style [(link)](https://zanichelli.atlassian.net/browse/CLAV-24)
----
=> fix(clav-24): fix style for z table

src/components/inputs/z-input-message/index.tsx, src/components/inputs/z-input-message/styles.css, src/index.html
----
This PR fixes z-input-message issue with html string content
----
=> fix: z-input-message fix

src/index.ts, src/utils/utils.ts
----
This function return one color name given a number id.
No abstract
Added a utils module containing the new exported function.
----
=> Add avatar color function

src/components/navigation/z-link/index.tsx, src/components/navigation/z-link/styles.css
----
Fix vars name
Definition of component:
https://share.goabstract.com/4b0bfcdf-eaa3-48c5-835f-4b3779379395?collectionLayerId=54ff6a45-b4c4-4d6d-af0b-61eca41fffec&mode=design&sha=latest
Definition of theme colors:
https://share.goabstract.com/7ecfaf18-36b8-4e35-b61b-11354423a9bd?collectionLayerId=ed279b61-8117-4bbc-9766-28fcd4a1b5c3&mode=design
----
=> FIX: fix colors for zlink

src/components/inputs/z-combobox/styles.css
----
Changes:
https://app.abstract.com/projects/fd370780-e659-11e8-99dc-0d08537c5fde/branches/cebfaffa-6c7b-4121-a2c0-4ad34cc1e355/commits/latest/files/9f586aa0-bd5b-4c12-9541-aed2e98a7a9c/layers/3CEB3AB8-D92D-4EDB-9FBA-0ED2A09C42CA?collectionId=91f0bc0c-8d75-4e1a-ae27-40c0de21a7d3&collectionLayerId=98a4c4ab-12cc-4f60-8823-c78b1ba56683&mode=build&selected=root-3CEB3AB8-D92D-4EDB-9FBA-0ED2A09C42CA
=> Feature: restyle of z-combobox

src/components.d.ts, src/components/modal/z-modal-login/index.tsx, src/components/modal/z-modal-login/readme.md
----
Due to improvement on idp-login-component, is needed small improvements
check applause issue: https://zanichelli.atlassian.net/browse/MLPR-129
----
=> chore: added password message and statusUpdate event

src/snowflakes/registro-table/z-registro-table/index.stories.mdx
----
- [x ] 6 - Not a Priority
- [x ] Bugfix (non-breaking change which fixes an issue)
----
=> fix: knobs uniform

src/beans/index.tsx, src/components.d.ts, src/snowflakes/registro-table/z-registro-table-expanded-row/index.stories.mdx, src/snowflakes/registro-table/z-registro-table-expanded-row/styles.css, src/snowflakes/registro-table/z-registro-table-header-row/styles.css, src/snowflakes/registro-table/z-registro-table-row/index.spec.ts, src/snowflakes/registro-table/z-registro-table-row/index.tsx, src/snowflakes/registro-table/z-registro-table-row/readme.md, src/snowflakes/registro-table/z-registro-table-row/styles.css
----
- extend click to the entire row
- fix expanding row button style
[Abstract link](https://app.abstract.com/share/71d02220-3ced-4fb6-b254-b20739903ece?mode=design&sha=3fe3a771ca59d8af3c65d0e73a99cbc46f0ffa15)
----
=> Feat - z-registro-table-row - fix expanding style

src/components/inputs/z-input/index.tsx, src/components/inputs/z-input/test-checkbox.spec.ts, src/components/inputs/z-input/test-radio.spec.ts, src/components/modal/z-modal/index.spec.ts, src/components/modal/z-modal/index.tsx, src/components/modal/z-modal/readme.md, src/components/modal/z-modal/styles.css, src/components/navigation/z-navigation-tabs/index.spec.ts, src/components/navigation/z-navigation-tabs/index.tsx
This PR solves some use of the `role` attribute, tags semantic and `aria` attributes.
----
=> fix a11y issues on some component

src/components/notification/z-tooltip/index.stories.css, src/components/notification/z-tooltip/index.tsx, src/components/notification/z-tooltip/readme.md, src/components/notification/z-tooltip/styles.css
Fix z-tooltip position when its container is scrollable and enhance positioning algorithm.
=> fix z-tooltip with scrollable container

src/components.d.ts, src/components/inputs/z-input-label/index.spec.ts, src/components/inputs/z-input-label/index.stories.mdx, src/components/inputs/z-input-label/index.tsx, src/components/inputs/z-input-label/readme.md, src/components/inputs/z-input/index.tsx, src/components/inputs/z-input/test-text.spec.ts, src/components/inputs/z-input/test-textarea.spec.ts, src/components/inputs/z-select/index.spec.ts, src/components/inputs/z-select/index.tsx
chore - z-input-label - added htmlFor attribute 
- z-input-label
- z-input type: text
- z-input type: text-area
- z-select
----
https://zanichelli.atlassian.net/browse/MYZ-8115
=> chore: MYZ-8115 htmlFor attribute to z-input-label

src/components/navigation/z-app-topbar/index.stories.mdx, src/components/navigation/z-app-topbar/styles.css, src/components/navigation/z-user-dropdown/styles.css
FIX - z-app-topbar - Wrong right margin without  z-app-switcher
----
----
=> fix: fix topbar style

src/snowflakes/registro-table/z-registro-table/index.stories.mdx, src/snowflakes/registro-table/z-registro-table/styles.css
----
When the table is loaded with no data but with first column populated, if there's only few rows the background can be not aligned with message ( see the screenshot below)
Before
Now
----
=> Fix - ZRegistroTable - Add default 

CHANGELOG.md, package.json
----
Fix contextual menu click behavior 
----
=> Fix  - ZRegistroTable - Handle contextual menu click

src/components/z-contextual-menu/index.tsx
----
Allow the user to set the color of contextual menu 
----
=> fix: contextual menu color

src/components/navigation/z-link/styles.css
----
Change visited color of the ZLink black variant
----
=> Chore - adjustment of the visited color to ZLink  black variant

src/components/z-popover/index.tsx
----
Initial positioning before this fix was calculated only after the first click; this affect the layout when the context menu was located outside the page.
With this fix the correct position is calculated after the component loading.
=> fix - z-popover - fix initial positioning

package.json, src/components/z-table/z-table-empty-box/index.tsx, src/components/z-table/z-table-empty-box/styles.css
----
Fix style of z-table-empty-box for mobile
- Change padding for the container
- Fix buttons styles
[Link](https://app.abstract.com/projects/4ad7d17c-8133-465e-9926-09f387eef58a/branches/334e0da7-ef9a-41be-a4d5-1493668c19c7/commits/latest/files/6ccb681e-7ab6-4f9d-8a06-c04e9ced92d1/layers/2B7326A5-36BB-41A3-97B7-23B3A8DE8FA6?collectionId=5d10c623-5e3e-4f3c-a900-669a717304ae&collectionLayerId=22a31369-f796-4e95-a342-70e7284f98f7)
----
=> Feat/CLAV-263 - z-table-empty-box - fix empty table style for mobile

src/components/z-table/z-table-empty-box/index.spec.ts
=> feat(CLAV-263): fix test

src/components/typography/z-body/index.spec.ts, src/components/typography/z-body/index.tsx, src/components/typography/z-heading/index.spec.ts, src/components/typography/z-heading/index.tsx
=> fix: added tabindex into z-body and z-heading components, fix tests

src/components/typography/z-typography/styles.css
=> fix: fixed focus element

src/components/buttons/z-chip/styles.css
=> fix z-chip style

src/components/buttons/z-toggle-switch/index.spec.ts, src/components/buttons/z-toggle-switch/index.stories.mdx, src/components/buttons/z-toggle-switch/index.tsx, src/components/buttons/z-toggle-switch/styles.css
=> fix: fix storybook

src/components.d.ts, src/components/notification/z-notification/index.spec.ts, src/components/notification/z-notification/index.stories.css, src/components/notification/z-notification/index.stories.mdx, src/components/notification/z-notification/index.tsx, src/components/notification/z-notification/readme.md, src/components/notification/z-notification/styles.css, src/components/notification/z-notification/test.e2e.ts, src/components/typography/z-body/readme.md, src/components/z-section-title/readme.md
Fix alignment of z-notification items. Add the `sticky` property to enable the `banner` variant of the z-notification component.
Migrate stories to Storybook's `Controls`.
https://app.abstract.com/projects/fd370780-e659-11e8-99dc-0d08537c5fde/branches/master/commits/latest/files/7e5534c1-96e2-44c2-98f8-965c34ee8835/layers/85C1A2BC-9E5D-43ED-BD11-AC28D82AF445?collectionId=ecb94390-fedf-428f-b021-4d452c356519&collectionLayerId=8fcfd09c-55be-4988-950c-f3958c80335d&mode=design&selected=root-E65DE96F-628F-4A19-8BDF-CAF38142290E
Before:
After:
=> Refactor - ZNotification

src/components.d.ts, src/components/buttons/z-chip/index.stories.mdx, src/components/buttons/z-chip/index.tsx, src/components/buttons/z-chip/readme.md
=> fix: fix key event

src/components.d.ts, src/components/z-pagination/index.stories.mdx, src/components/z-pagination/index.tsx, src/components/z-pagination/styles.css
----
https://share.goabstract.com/e78ab14b-cf72-4f84-81c1-d1066a75305a?collectionLayerId=11dc8c20-e95c-41a5-9407-0ca3c347c281&mode=design
Add new control for z-pagination:
- skip
- edges
----
=> ECOZ-1561 & 1562 : new controls skip edges for z-pagination

src/snowflakes/myz/card/z-myz-card-dictionary/styles.css, src/snowflakes/myz/card/z-myz-card/styles.css
=> fix: fix overflow for z-myz-dictionary-card

src/components.d.ts, src/components/z-date-picker/index.stories.mdx, src/components/z-date-picker/index.tsx
this PR adds aria-label and label props for accessibility.
----
=> chore: add labels on zDatePicker

src/components/inputs/z-input/styles-general.css
=> Fix - ZInput - Added input label size and weight

src/components/buttons/z-button/index.stories.mdx, src/components/buttons/z-button/index.tsx, src/components/buttons/z-button/styles.css, src/components/z-contextual-menu/styles.css
Fix alle classi css dello z-button: non avendo più `shadow: true`, le classi con lo stesso nome definite nei prodotti, influenzano gli elementi interni dello z-button. Essendo nomi abbastanza comuni (`container`, `primary`, `big`, ...) è facile che qualcosa si rompa, quindi meglio dare dei nomi più univoci come `z-button--container` così da evitare il problema.
Fix a dimensione e allineamento del trigger button interno allo z-contextual-menu: nei casi in cui serve cambiare la dimensione del componente (es: fare un bottone un po' più grande o con sfondo diverso), il bottone non rispetta la dimensione e l'allineamento.
=> fix: z-button unsafe css classes; z-contextual-menu style

src/index.ts
----
Added beans export in main index.ts for external use
----
=> chore: added beans export

src/components/inputs/z-combobox/styles.css
----
Fix height of combobox when prop fixed is setted to true
----
=> Fix - ZCombobox - height: fix height when prop fixed is true

src/components/z-section-title/styles.css
----
Fix css style when uppercase is false
----
=> Fix - z-section-title: fix css style for uppercase prop

src/components/inputs/z-input-message/styles.css
fix - z-input-message - fix component min-height and icon vertical alignment
----
The fix gives to z-input-message a consistent height when filled with text or without it and aligns the icon and the message.
----
=> fix: z-input-error-message

src/components/file-upload/z-dragdrop-area/index.spec.ts, src/components/file-upload/z-dragdrop-area/index.tsx, src/components/file-upload/z-file-upload/index.spec.ts, src/components/file-upload/z-file-upload/index.tsx, src/components/file-upload/z-file-upload/styles.css, src/components/file-upload/z-file-upload/test.e2e.ts, src/components/z-popover/index.tsx
Added shadow dom to ZFileUpload component to fix render problems with slot.
Also fixed ZPopover outside click handling (Firefox/Safari bug)
=> Fix - ZFileUpload - added shadow dom

src/components/file-upload/z-file-upload/index.tsx
=> ZFileUpload - Fix type prop handing and console error

src/components/file-upload/z-file-upload/index.stories.mdx, src/components/file-upload/z-file-upload/index.tsx
=> Fix - FileUpload - Fix rerender and focus problem

package.json, src/grid/index.stories.css, src/grid/index.stories.mdx, yarn.lock
Add grid system story to test grid system.
This PR has to be checked after merging https://github.com/ZanichelliEditore/design-tokens/pull/14.
=> Add Grid System story

src/beans/index.tsx, src/components.d.ts, src/components/inputs/z-select/index.spec.ts, src/components/inputs/z-select/index.stories.mdx, src/components/inputs/z-select/index.tsx, src/components/inputs/z-select/styles.css, src/index.html
add the possibility to organize z-list-elements within z-list-groups
=> Feat - ZSelect - add ZListGroup mode

src/beans/index.tsx, src/components.d.ts, src/components/list/z-list-element/index.spec.ts, src/components/list/z-list-element/index.stories.mdx, src/components/list/z-list-element/index.tsx, src/components/list/z-list-element/styles.css, src/components/list/z-list-group/index.spec.ts, src/components/list/z-list-group/index.stories.mdx, src/components/list/z-list-group/index.tsx, src/components/list/z-list/index.spec.ts, src/components/list/z-list/index.stories.mdx, src/components/list/z-list/index.tsx, src/index.html
Fix two bugs: wrong behaviour with list size prop and wrong effect while clicking an interactive list element
Add list-style prop to add the possibility to insert ordered or unsorted lists
=> Feat - ZList - fix bugs and add list-style prop

src/components/z-offcanvas/styles.css
Fix - Z-Offcanvas - fix wrong z-index 
=> fix: z-index

src/beans/index.tsx, src/components.d.ts, src/components/inputs/z-combobox/index.stories.mdx, src/components/inputs/z-combobox/index.tsx, src/components/inputs/z-combobox/readme.md, src/components/inputs/z-select/index.tsx, src/components/list/z-list-group/readme.md
Add support to group z-combobox items in categories
=> Feat - Added groups to z-combobox

src/components/inputs/z-combobox/index.stories.mdx
Minor import fix to make "Show code" button appear in Storybook
=> Chore - ZCombobox - Fix storybook

src/components/z-table/z-table-row/index.tsx, src/components/z-table/z-table/index.stories.mdx
=> chore: improved expand row behaviour

package.json, src/components/z-popover/index.tsx, yarn.lock
This PR fixes and enhances the auto-close behavior of the z-popover component (reflecting the fix also to the z-tooltip component). 
The `getElementTree` helper function wasn't able to find all parents of the clicked element when handling clicks outside of the popover content, because of the shadow DOM closed mode. Event's `composedPath` method, instead, correctly looks at target element's ancestors.
Another little enhancement was included in this PR: clicks on the element the popover is bound to, now won't propagate the click event, to prevent ugly close/reopen glitches (that click would have triggered the auto-close and, propagating to the trigger element, also an instant reopen).
=> Fix z-tooltip/z-popover auto close

src/components/z-cover-hero/index.tsx, src/components/z-cover-hero/styles.css
=> chore: allow to configure cover hero's min height

src/components.d.ts, src/components/inputs/z-select/index.spec.ts, src/components/inputs/z-select/index.tsx, src/components/inputs/z-select/readme.md, src/components/inputs/z-select/styles.css, src/index.html
=> Feature/z select/add reset item

src/components.d.ts, src/components/modal/z-modal/index.spec.ts, src/components/modal/z-modal/index.stories.css, src/components/modal/z-modal/index.stories.mdx, src/components/modal/z-modal/index.tsx, src/components/modal/z-modal/readme.md, src/components/modal/z-modal/styles.css
Handle modal navigation and ESC key press.
=> chore: handle z-modal accessibility

src/beans/index.tsx, src/components/inputs/z-input/styles-general.css, src/components/inputs/z-select/index.stories.mdx, src/components/modal/z-modal/styles.css
=> Fix: z-modal mobile style

src/beans/index.tsx, src/components.d.ts, src/components/z-breadcrumb/index.spec.ts, src/components/z-breadcrumb/index.stories.mdx, src/components/z-breadcrumb/index.tsx, src/components/z-breadcrumb/styles.css, src/index.html
Add the mobile version of Breadcrumb component
[Figma](https://www.figma.com/file/w51ZwDwLNEt0yamar2sRRQ/Nuovi-Componenti-e-Pattern?node-id=616-2498)
=> Feature - ZBreadcrumb - add mobile version of component

package.json, src/components/buttons/z-button-sort/styles.css, src/components/buttons/z-toggle-button/styles.css, src/components/indicators/z-stepper-item/styles.css, src/components/z-card/styles.css, src/snowflakes/myz/card/z-myz-card-icon/styles.css, yarn.lock
=> Fix: focus box-shadow

.storybook/preview.js
=> chore(storybook): alphabetically sort storybook entries

.stylelintrc.json, src/beans/index.tsx, src/components.d.ts, src/components/navigation/z-link/readme.md, src/components/z-book-card/index.spec.ts, src/components/z-book-card/index.stories.mdx, src/components/z-book-card/index.tsx, src/components/z-book-card/readme.md, src/components/z-book-card/styles.css, src/pages/book-cards.html
=> [WIP] Feature/z book card expanded

src/components/z-card/index.stories.mdx, src/components/z-card/index.tsx, src/components/z-card/styles.css
Chore - z-card - adding css var to edit padding in text variant
=> feat: added css var for padding in z-card text version

src/components/z-book-card/styles.css
=> feat: prevent overflow text for isbn and ribbon

src/components.d.ts, src/components/navigation/z-app-header/index.tsx, src/components/navigation/z-app-header/readme.md
=> Chore - ZAppHeader - Added `searchString` prop

src/components/z-card/styles.css
Removes constraint in order to let the user set their choices.
=> Fix - Zcard - Removes constraint on width actions slot of z-card

src/components/icons/z-icon/readme.md, src/components/panel/z-panel-elem/index.spec.ts, src/components/panel/z-panel-elem/index.stories.mdx, src/components/panel/z-panel-elem/index.tsx, src/components/panel/z-panel-elem/readme.md, src/components/panel/z-panel-elem/styles.css, src/deprecated/z-link/readme.md
=> chore: remove z-link from z-panel-elem

src/components.d.ts, src/components/z-book-card/index.spec.ts, src/components/z-book-card/index.tsx, src/components/z-book-card/readme.md
=> Chore/z book card add isbnLabel

src/components/z-book-card/index.stories.mdx
Updated ZBookCard's storybook following [PR 386](https://github.com/ZanichelliEditore/design-system/pull/386)
=> chore: add isbnLabel prop to zbookcard storybook

src/components/z-accordion/index.stories.mdx, src/components/z-accordion/index.tsx, src/components/z-accordion/styles.css
Questa MR aggiunge delle variabili css per personalizzare il componente z-accordion.
=> Chore - z-accordion - add css vars

package.json, src/components/css-components/readme.md, src/components/css-components/z-fab/index.stories.css, src/components/css-components/z-fab/index.stories.mdx, src/components/css-components/z-link/index.stories.mdx, src/components/icons/icons.stories.mdx, src/components/navigation/tabs/z-navigation-tabs/index.stories.css, src/components/navigation/tabs/z-navigation-tabs/index.stories.mdx, src/components/navigation/tabs/z-navigation-tabs/index.tsx, src/components/navigation/tabs/z-navigation-tabs/styles.css, src/components/panel/z-panel-elem/index.spec.ts, src/components/panel/z-panel-elem/index.tsx, src/components/table/cells/z-td/index.tsx, src/components/table/z-table/index.stories.mdx, src/components/z-carousel/index.tsx, yarn.lock
This PR add documentation and some storybook stories for the `ZFab` CSS component, that's stored in the tokens repository.
Since they were missing, some stories have been added also for the `ZLink`.
In addition, some accessibility and style fixes to other components has been included.
=> Feat - ZFab - stories

src/components/navigation/tabs/z-navigation-tabs/index.tsx
=> fix: z-navigation-tabs fix keyboard navigation

src/components/navigation/tabs/z-navigation-tabs/index.tsx
=> fix: z-navigation-tabs with active tab selected

src/components/navigation/z-app-header/index.spec.ts, src/components/navigation/z-app-header/index.stories.mdx, src/components/navigation/z-app-header/index.tsx, src/components/navigation/z-app-header/readme.md, src/components/navigation/z-app-header/styles.css
Add the possibility to have also a top subtitle on the ZAppHeader.
=> Added top subtitle on App Header

src/components.d.ts, src/components/date-picker/z-range-picker/index.spec.ts, src/components/date-picker/z-range-picker/index.stories.mdx, src/components/date-picker/z-range-picker/index.tsx, src/components/date-picker/z-range-picker/readme.md
Added placeholder and disabled props to z-range-picker component
Props needed by some applications
=> Z range picker/added placeholder and readonly

src/components/z-book-card/styles.css
Changed height in search variant z-book-card to make more clear CTA
=> chore: update height in z-book-card

.github/workflows/release.yml
The `workflow_dispatch` hook works only when the YAML file is on the default branch.
=> Feat/release GitHub action

package.json, yarn.lock
Update version design tokens with new palette subjects colors
=> Update version design tokens

package.json, yarn.lock
Updated the package.json with the new version.
=> Chore - Updated design token version

src/components.d.ts, src/components/buttons/z-button/index.spec.ts, src/components/buttons/z-button/index.tsx, src/components/icons/z-icon/readme.md, src/components/z-card/readme.md, src/components/z-carousel/index.stories.css, src/components/z-carousel/index.stories.mdx, src/components/z-carousel/index.tsx, src/components/z-carousel/readme.md, src/components/z-carousel/styles.css
This PR implements the visual changes and new features of the ZCarousel component:
- show navigation buttons only on over with the new prop `fixedArrows`
- enable "infinite scroll" with the new prop `infinite` that allows navigating from the last to the first item by navigating forward and vice versa by navigating backwards
- increase the size of the dot buttons
- use the correct arrow icon in all navigation buttons
- enable shadowDOM as a workaround to the bug with the dynamic rendering of slotted items
- handle adding/removing items via the `slotchange` event
The stories have been improved, and a control to add/remove items has also been added in order to try different carousel sizes.
https://www.figma.com/file/w51ZwDwLNEt0yamar2sRRQ/Nuovi-Componenti-e-Pattern?type=design&node-id=6088-81 …
=> Refactor - ZCarousel improvements

src/components/z-anchor-navigation/index.tsx, src/components/z-anchor-navigation/styles.css, src/components/z-breadcrumb/index.spec.ts, src/components/z-breadcrumb/index.stories.mdx, src/components/z-breadcrumb/index.tsx, src/components/z-breadcrumb/styles.css
Use iconset chevron and fix the size of the icons, fix some spacing and focus shadow, remove wrong left padding that caused misalignment with the content of the apps.
https://albe.zanichelli.it/485b31545/p/994239-breadcrumb/b/327566
old:
new:
=> chore - ZBreadcrumb - style and code enhancements

.github/workflows/storybook.yml
The release of Storybook is currently launched manually. With this PR it is automated and launched following a successful release.
How the triggering event works:
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
=> feat: add Storybook deploy after a successful release process

package.json, yarn.lock
=> chore: fix for design tokens

package.json, yarn.lock
=> Update design tokens to 1.2.6

src/components/z-stepper-item/index.stories.ts, src/components/z-stepper/index.stories.ts, src/components/z-stepper/index.tsx, src/components/z-stepper/readme.md, src/components/z-tag/index.stories.ts
chore - z-stepper - add examples to documentation
Add needed examples to the z-stepper documentation, showing the component in his varius states.
=> chore: add examples to z-stepper documentation

src/components/css-components/z-fab/index.stories.ts, src/components/css-components/z-fab/styles.css, src/components/css-components/z-link/styles.css
=> Add focus shadow to z-fab and z-link

src/components/file-upload/z-dragdrop-area/styles.css, src/components/file-upload/z-file-upload/styles.css, src/components/z-card/styles.css, src/components/z-modal/styles.css, src/components/z-searchbar/styles.css
Fix problems with the focus in some components that lead to unexpected behavior
=> fix: focus problems

src/components.d.ts, src/components/z-card/index.spec.ts, src/components/z-card/index.stories.css, src/components/z-card/index.stories.ts, src/components/z-card/index.tsx, src/components/z-card/styles.css
=> Test - ZCard - enhance tests

src/components/z-combobox/styles.css
fix focus combobox when open for accessibility
=> fix: focus combobox when open

src/components/z-app-header/index.stories.ts, src/components/z-app-header/index.tsx, src/components/z-app-header/styles.css, src/components/z-menu-section/index.spec.ts, src/components/z-menu-section/index.tsx, src/components/z-menu-section/styles.css, src/components/z-menu/index.spec.ts, src/components/z-menu/index.tsx, src/components/z-menu/styles.css
=> Fix - ZAppHeader - product logo style and improved keyboard navigation

src/components/z-info-reveal/test.e2e.ts
Add e2e tests for z-info-reveal.
=> Add e2e test for z-info-reveal

src/components/z-pagination/test.e2e.ts
Add tests e2e for z-pagination
=> chore: tests e2e z-pagination

docs/themes/index.stories.ts, src/components/css-components/index.css, src/components/css-components/z-scrollbar/index.stories.css, src/components/css-components/z-scrollbar/index.stories.ts, src/components/css-components/z-scrollbar/styles.css, src/components/z-combobox/styles.css, src/components/z-input/index.tsx, src/components/z-input/styles-textarea.css, src/components/z-input/test-textarea.spec.ts, src/components/z-modal/styles.css, src/components/z-offcanvas/index.spec.ts, src/components/z-offcanvas/index.tsx, src/components/z-offcanvas/styles.css, src/components/z-searchbar/styles.css, src/components/z-select/index.spec.ts, src/components/z-select/index.tsx, src/components/z-select/styles.css
Add new css component for styling scrollbars
=> feature: z-scrollbar - add class component

src/components.d.ts, src/components/book-card/z-book-card/index.tsx, src/components/book-card/z-book-card/readme.md, src/components/book-card/z-book-card/styles.css, src/pages/book-cards.html
=> Fix - ZBookCard  - Add reflowable prop

MIGRATION.md, src/beans/index.tsx, src/components.d.ts, src/components/book-card/z-book-card/index.stories.ts, src/components/book-card/z-book-card/index.tsx, src/components/book-card/z-book-card/readme.md, src/components/book-card/z-book-card/styles.css, src/components/book-card/z-book-card/test.e2e.ts, src/components/z-icon/readme.md, src/components/z-tag/readme.md, src/pages/book-cards.html
ZBookCard refactoring, as requested by designers
https://www.figma.com/design/w51ZwDwLNEt0yamar2sRRQ/branch/To5LlfWLba1S62IkOS3VxM/Nuovi-Componenti-e-Pattern?node-id=13548-13619&p=f&m=dev
Changes are breaking only for myZanichelli
=> Chore - ZBookCard - Refactoring

src/components/z-select/index.tsx
=> chore: removed unused icon

src/components/z-carousel/test.e2e.ts, src/components/z-select/index.tsx, src/components/z-select/test.e2e.ts
Fix selection with ENTER in ZSelect
This change solve a problem with keyboard enter selection in zselect options
=> Fix selection with ENTER in ZSelect

src/components.d.ts, src/components/z-pagination/index.stories.ts, src/components/z-pagination/index.tsx, src/components/z-pagination/styles.css, src/components/z-pagination/test.e2e.ts
Added two new CSS variables to customize the background color of the pagination component, in default and hover states. 
Fixed the scroll where the pagination was not working correctly.
=> Chore - z-pagination - background and scroll

src/components/z-stepper-item/index.tsx
CSS uses reflect syntax without reflect attributes - the component is not working properly in React 19
=> Fix - ZStepperItem - Add reflect to props

src/components/z-anchor-navigation/index.tsx
The initial design of the component required a smaller height of the collapsed version.
=> fix: change anchor button size to `small`

src/components/book-card/z-book-card/index.tsx, src/components/book-card/z-book-card/styles.css, src/components/book-card/z-book-card/test.e2e.ts, src/pages/book-cards.html
Fix the focus and click behavior on the image when the cover overlay is present.
=> fix: focus and click on image

src/components/list/z-list-element/styles.css, src/components/z-select/styles.css
[ZListElement] fix the focus behaviour when more than one ZListElement are used.
Before the fix:
- ZList with 3 elements
- ZSelect with focused top element
fixed behaviour:
- ZList with 3 elements
-ZSelect with focused top element
=> fix: prevent focus overlap in zlistelement
